[package]
name = "d12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_utils = { path = "../aoc_utils/" }
memoize = "0.4.1"

[dev-dependencies]
rstest = "0.18.2"
